import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"
import { createServerSupabase } from "@/server/supabase/server"

function getAdmin() {
  return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { autoRefreshToken: false, persistSession: false } })
}

export async function GET(request: NextRequest) {
  const supabase = await createServerSupabase()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const academyId = user.app_metadata?.academy_id as string
  if (!academyId) return NextResponse.json({ error: "No academy" }, { status: 400 })

  const month = request.nextUrl.searchParams.get("month") ?? new Date().toISOString().slice(0, 7)
  const [year, mon] = month.split("-").map(Number)
  const startDate = `${month}-01`
  const endDate = `${year}-${String(mon! + 1).padStart(2, "0")}-01`

  const admin = getAdmin()

  const [academyRes, sessionsRes, _attendanceRes] = await Promise.all([
    admin.from("academies").select("name").eq("id", academyId).single(),
    admin.from("class_sessions").select("id, class_id, date, start_time, end_time, status, attendance_count").eq("academy_id", academyId).gte("date", startDate).lt("date", endDate).order("date"),
    admin.from("attendance").select("session_id, member_id").eq("academy_id", academyId),
  ])

  const sessions = sessionsRes.data ?? []
  const classIds = [...new Set(sessions.map((s) => s.class_id))]
  const { data: classes } = await admin.from("classes").select("id, name").in("id", classIds.length > 0 ? classIds : ["none"])
  const classMap = new Map((classes ?? []).map((c) => [c.id, c.name]))

  const totalSessions = sessions.filter((s) => s.status === "completed").length
  const totalAttendance = sessions.reduce((s, a) => s + a.attendance_count, 0)

  const rows = sessions.map((s) => `
    <tr>
      <td style="padding:6px 12px;border-bottom:1px solid #eee;">${s.date}</td>
      <td style="padding:6px 12px;border-bottom:1px solid #eee;">${classMap.get(s.class_id) ?? "—"}</td>
      <td style="padding:6px 12px;border-bottom:1px solid #eee;">${s.start_time}–${s.end_time}</td>
      <td style="padding:6px 12px;border-bottom:1px solid #eee;">${s.status}</td>
      <td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:center;">${s.attendance_count}</td>
    </tr>
  `).join("")

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Attendance Report — ${month}</title>
    <style>body{font-family:system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px}table{width:100%;border-collapse:collapse}th{background:#f3f4f6;padding:8px 12px;text-align:left;font-size:13px}td{font-size:13px}@media print{button{display:none}}</style>
  </head><body>
    <div style="display:flex;justify-content:space-between;align-items:center;">
      <div><h1 style="margin:0;font-size:24px;">${academyRes.data?.name ?? "Academy"}</h1><p style="color:#888;">Attendance Report — ${month}</p></div>
      <button onclick="window.print()" style="padding:8px 16px;background:#6366f1;color:#fff;border:none;border-radius:8px;cursor:pointer;">Print / Save PDF</button>
    </div>
    <div style="display:flex;gap:24px;margin:24px 0;">
      <div style="flex:1;background:#f0fdf4;border-radius:8px;padding:16px;"><div style="font-size:24px;font-weight:700;">${totalSessions}</div><div style="color:#888;font-size:13px;">Completed sessions</div></div>
      <div style="flex:1;background:#eff6ff;border-radius:8px;padding:16px;"><div style="font-size:24px;font-weight:700;">${totalAttendance}</div><div style="color:#888;font-size:13px;">Total check-ins</div></div>
      <div style="flex:1;background:#fefce8;border-radius:8px;padding:16px;"><div style="font-size:24px;font-weight:700;">${totalSessions > 0 ? Math.round(totalAttendance / totalSessions) : 0}</div><div style="color:#888;font-size:13px;">Avg per session</div></div>
    </div>
    <table><thead><tr><th>Date</th><th>Class</th><th>Time</th><th>Status</th><th style="text-align:center;">Attendance</th></tr></thead><tbody>${rows}</tbody></table>
    <p style="color:#aaa;font-size:11px;margin-top:32px;">Generated by GrapplingFlow · ${new Date().toISOString().split("T")[0]}</p>
  </body></html>`

  return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } })
}
